### ISSUE TITLE
Add customGPT-name

### ISSUE THREAD

**Issue by mdabir1203** [devisasari/awesome-gpt-store#36]
[Cultural Compass](https://github.com/mdabir1203/Cultural-Compass) - 

Your AI-Driven Global Cultural Guide

Cultural Compass is an AI-driven guide specifically tailored to help users navigate and understand the rich diversity of European cultures. It provides insightful, accurate, and respectful guidance on various aspects of **international etiquette and customs**, **business practices**, and **communication styles**.

**Comment by devisasari** [comment]
Nice. Can you add it to the repo as a pull request, not as an issue since it's not an issue?
